all: \
	topojson/ne_10m_admin_0_antarctic_claim_limit_lines.json \
	topojson/ne_10m_admin_0_antarctic_claims.json \
	topojson/ne_10m_admin_0_boundary_lines_disputed_areas.json \
	topojson/ne_10m_admin_0_boundary_lines_land.json \
	topojson/ne_10m_admin_0_boundary_lines_map_units.json \
	topojson/ne_10m_admin_0_boundary_lines_maritime_indicator.json \
	topojson/ne_10m_admin_0_countries.json \
	topojson/ne_10m_admin_0_countries_lakes.json \
	topojson/ne_10m_admin_0_disputed_areas.json \
	topojson/ne_10m_admin_0_disputed_areas_scale_rank_minor_islands.json \
	topojson/ne_10m_admin_0_label_points.json \
	topojson/ne_10m_admin_0_map_subunits.json \
	topojson/ne_10m_admin_0_map_units.json \
	topojson/ne_10m_admin_0_pacific_groupings.json \
	topojson/ne_10m_admin_0_scale_rank.json \
	topojson/ne_10m_admin_0_scale_rank_minor_islands.json \
	topojson/ne_10m_admin_0_seams.json \
	topojson/ne_10m_admin_0_sovereignty.json \
	topojson/ne_10m_admin_1_seams.json \
	topojson/ne_10m_admin_1_states_provinces_lakes_shp.json \
	topojson/ne_10m_admin_1_states_provinces_lines.json \
	topojson/ne_10m_admin_1_states_provinces_shp.json \
	topojson/ne_10m_airports.json \
	topojson/ne_10m_antarctic_ice_shelves_lines.json \
	topojson/ne_10m_antarctic_ice_shelves_polys.json \
	topojson/ne_10m_bathymetry_A_10000.json \
	topojson/ne_10m_bathymetry_B_9000.json \
	topojson/ne_10m_bathymetry_C_8000.json \
	topojson/ne_10m_bathymetry_D_7000.json \
	topojson/ne_10m_bathymetry_E_6000.json \
	topojson/ne_10m_bathymetry_F_5000.json \
	topojson/ne_10m_bathymetry_G_4000.json \
	topojson/ne_10m_bathymetry_H_3000.json \
	topojson/ne_10m_bathymetry_I_2000.json \
	topojson/ne_10m_bathymetry_J_1000.json \
	topojson/ne_10m_bathymetry_K_200.json \
	topojson/ne_10m_bathymetry_L_0.json \
	topojson/ne_10m_coastline.json \
	topojson/ne_10m_geographic_lines.json \
	topojson/ne_10m_geography_marine_polys.json \
	topojson/ne_10m_geography_regions_elevation_points.json \
	topojson/ne_10m_geography_regions_points.json \
	topojson/ne_10m_geography_regions_polys.json \
	topojson/ne_10m_glaciated_areas.json \
	topojson/ne_10m_graticules_10.json \
	topojson/ne_10m_graticules_15.json \
	topojson/ne_10m_graticules_1.json \
	topojson/ne_10m_graticules_20.json \
	topojson/ne_10m_graticules_30.json \
	topojson/ne_10m_graticules_5.json \
	topojson/ne_10m_lakes_europe.json \
	topojson/ne_10m_lakes.json \
	topojson/ne_10m_lakes_historic.json \
	topojson/ne_10m_lakes_north_america.json \
	topojson/ne_10m_lakes_pluvial.json \
	topojson/ne_10m_land.json \
	topojson/ne_10m_land_ocean_label_points.json \
	topojson/ne_10m_land_ocean_seams.json \
	topojson/ne_10m_land_scale_rank.json \
	topojson/ne_10m_minor_islands_coastline.json \
	topojson/ne_10m_minor_islands.json \
	topojson/ne_10m_minor_islands_label_points.json \
	topojson/ne_10m_ocean.json \
	topojson/ne_10m_ocean_scale_rank.json \
	topojson/ne_10m_parks_and_protected_lands_area.json \
	topojson/ne_10m_parks_and_protected_lands_line.json \
	topojson/ne_10m_parks_and_protected_lands_point.json \
	topojson/ne_10m_parks_and_protected_lands_scale_rank.json \
	topojson/ne_10m_playas.json \
	topojson/ne_10m_populated_places.json \
	topojson/ne_10m_populated_places_simple.json \
	topojson/ne_10m_ports.json \
	topojson/ne_10m_railroads.json \
	topojson/ne_10m_railroads_north_america.json \
	topojson/ne_10m_reefs.json \
	topojson/ne_10m_rivers_europe.json \
	topojson/ne_10m_rivers_lake_centerlines.json \
	topojson/ne_10m_rivers_lake_centerlines_scale_rank.json \
	topojson/ne_10m_rivers_north_america.json \
	topojson/ne_10m_roads.json \
	topojson/ne_10m_roads_north_america.json \
	topojson/ne_10m_time_zones.json \
	topojson/ne_10m_urban_areas.json \
	topojson/ne_10m_urban_areas_landscan.json \
	topojson/ne_10m_wgs84_bounding_box.json \
	topojson/ne_110m_admin_0_boundary_lines_land.json \
	topojson/ne_110m_admin_0_countries.json \
	topojson/ne_110m_admin_0_countries_lakes.json \
	topojson/ne_110m_admin_0_map_units.json \
	topojson/ne_110m_admin_0_pacific_groupings.json \
	topojson/ne_110m_admin_0_scale_rank.json \
	topojson/ne_110m_admin_0_sovereignty.json \
	topojson/ne_110m_admin_0_tiny_countries.json \
	topojson/ne_110m_admin_1_states_provinces_lakes_shp.json \
	topojson/ne_110m_admin_1_states_provinces_lines.json \
	topojson/ne_110m_admin_1_states_provinces_shp.json \
	topojson/ne_110m_admin_1_states_provinces_shp_scale_rank.json \
	topojson/ne_110m_coastline.json \
	topojson/ne_110m_geographic_lines.json \
	topojson/ne_110m_geography_marine_polys.json \
	topojson/ne_110m_geography_regions_elevation_points.json \
	topojson/ne_110m_geography_regions_points.json \
	topojson/ne_110m_geography_regions_polys.json \
	topojson/ne_110m_glaciated_areas.json \
	topojson/ne_110m_graticules_10.json \
	topojson/ne_110m_graticules_15.json \
	topojson/ne_110m_graticules_1.json \
	topojson/ne_110m_graticules_20.json \
	topojson/ne_110m_graticules_30.json \
	topojson/ne_110m_graticules_5.json \
	topojson/ne_110m_lakes.json \
	topojson/ne_110m_land.json \
	topojson/ne_110m_ocean.json \
	topojson/ne_110m_populated_places.json \
	topojson/ne_110m_populated_places_simple.json \
	topojson/ne_110m_rivers_lake_centerlines.json \
	topojson/ne_110m_wgs84_bounding_box.json \
	topojson/ne_50m_admin_0_boundary_lines_disputed_areas.json \
	topojson/ne_50m_admin_0_boundary_lines_land.json \
	topojson/ne_50m_admin_0_boundary_lines_maritime_indicator.json \
	topojson/ne_50m_admin_0_boundary_map_units.json \
	topojson/ne_50m_admin_0_breakaway_disputed_areas.json \
	topojson/ne_50m_admin_0_countries.json \
	topojson/ne_50m_admin_0_countries_lakes.json \
	topojson/ne_50m_admin_0_map_subunits.json \
	topojson/ne_50m_admin_0_map_units.json \
	topojson/ne_50m_admin_0_pacific_groupings.json \
	topojson/ne_50m_admin_0_scale_rank.json \
	topojson/ne_50m_admin_0_sovereignty.json \
	topojson/ne_50m_admin_0_tiny_countries.json \
	topojson/ne_50m_admin_0_tiny_countries_scale_rank.json \
	topojson/ne_50m_admin_1_states_provinces_lakes_shp.json \
	topojson/ne_50m_admin_1_states_provinces_lines.json \
	topojson/ne_50m_admin_1_states_provinces_shp.json \
	topojson/ne_50m_admin_1_states_provinces_shp_scale_rank.json \
	topojson/ne_50m_antarctic_ice_shelves_lines.json \
	topojson/ne_50m_antarctic_ice_shelves_polys.json \
	topojson/ne_50m_coastline.json \
	topojson/ne_50m_geographic_lines.json \
	topojson/ne_50m_geography_marine_polys.json \
	topojson/ne_50m_geography_regions_elevation_points.json \
	topojson/ne_50m_geography_regions_points.json \
	topojson/ne_50m_geography_regions_polys.json \
	topojson/ne_50m_glaciated_areas.json \
	topojson/ne_50m_graticules_10.json \
	topojson/ne_50m_graticules_15.json \
	topojson/ne_50m_graticules_1.json \
	topojson/ne_50m_graticules_20.json \
	topojson/ne_50m_graticules_30.json \
	topojson/ne_50m_graticules_5.json \
	topojson/ne_50m_lakes.json \
	topojson/ne_50m_lakes_historic.json \
	topojson/ne_50m_land.json \
	topojson/ne_50m_ocean.json \
	topojson/ne_50m_playas.json \
	topojson/ne_50m_populated_places.json \
	topojson/ne_50m_populated_places_simple.json \
	topojson/ne_50m_rivers_lake_centerlines.json \
	topojson/ne_50m_rivers_lake_centerlines_scale_rank.json \
	topojson/ne_50m_urban_areas.json \
	topojson/ne_50m_wgs84_bounding_box.json \


topojson/%.json: geojson/%.geojson
	node_modules/.bin/topojson \
		-o $@ \
		-p \
		-- $< \

clean:
	rm -rf topojson/*